CREATE TABLE reminders (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id),
  reminder_date date,
  reminder_time time,
  reminder_text text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);