-- Create the User table
CREATE TABLE "User" (
  username TEXT NOT NULL,
  email TEXT NOT NULL,
  "passwordHash" TEXT NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL,
  "displayName" TEXT,
  "profilePictureUrl" TEXT,
  bio TEXT,
  "lastLoginAt" TIMESTAMPTZ,
  PRIMARY KEY (username)
);

-- Create the Habit table
CREATE TABLE "Habit" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user" TEXT NOT NULL REFERENCES "User"(username),
  name TEXT NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL,
  "targetFrequency" TEXT NOT NULL,
  description TEXT,
  "reminderTime" TIMESTAMPTZ
);

-- Create the HabitLog table
CREATE TABLE "HabitLog" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user" TEXT NOT NULL REFERENCES "User"(username),
  "habit" BIGINT NOT NULL REFERENCES "Habit"(id),
  "logDate" DATE NOT NULL,
  status TEXT NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL,
  reflection TEXT,
  "pointsEarned" INT
);

-- Create the Group table
CREATE TABLE "Group" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  creator TEXT NOT NULL REFERENCES "User"(username),
  name TEXT NOT NULL,
  description TEXT NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL,
  "isPublic" BOOLEAN NOT NULL,
  "imageUrl" TEXT,
  "joinCode" TEXT
);

-- Create the GroupMember table
CREATE TABLE "GroupMember" (
  "user" TEXT NOT NULL REFERENCES "User"(username),
  "group" BIGINT NOT NULL REFERENCES "Group"(id),
  "joinedAt" TIMESTAMPTZ NOT NULL,
  role TEXT,
  PRIMARY KEY ("user", "group")
);
